config/routes.rb
Rails.application.routes.draw do
  get 'memberships/create'
  get 'memberships/destroy'

  root to: 'pages#profile'
  get '/search', to: 'pages#search'
  get '/profile', to: 'pages#profile'

  post '/check_invitation', to: 'invitations#check_invitation'

  devise_for :users

  resources :groups do
    resources :posts, only: [:create]
    resources :receipts
  end
  resources :invitations, only: [:create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :invitations, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :receipts

  def member?(user)
    members.include?(user)
  end

  def has_admin?
    memberships.admin.present?
  end

  def set_admin
    memberships.first.admin!
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @membership = current_user.memberships.build(group_id: @group.id)
        if @membership.save
          @membership.admin!
          format.html { redirect_to @group,
                        notice: 'Group created, you are now admin of this group.'}
        else
          format.html { render :new }
        end
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      redirect_to root_path
    else
    end
  end

  def show
    @group = Group.find(params[:id])
    authorize! :read, @group
    @admins = User.admins(@group)
    @members = @group.members - @admins
    @posts = @group.posts.order(created_at: :desc).decorate
    @receipts = @group.receipts.decorate
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_admin.html.haml
%p= admin.email

app/views/groups/_member.html.haml
%li.member= member.email

app/views/groups/new.html.haml
.jumbotron
  .container
    .row
      .col-md-4.offset-md-4
        = simple_form_for @group do |g|
          .form-group
            = g.input :name, input_html: { class: 'form-control', placeholder: "Group name" }
          .form-group
            = g.input :description, as: :text, input_html: { class: 'form-control', placeholder: "Description"}
          .form-group
            = g.button :submit, "Create group", class: "btn btn-md btn-primary btn-block"

app/views/groups/show.html.haml
.jumbotron
  .container
    .row
      .col-md-6.text-center
        %h1.display-3= @group.name
        %p= @group.description
        %p
          = link_to 'Create new receipt »', new_group_receipt_path(@group), class: "btn btn-primary btn-lg"
        - if @group.member?(current_user)
          = link_to 'quit group', memberships_destroy_path(user_id: current_user.id, group_id: @group.id), class: "btn btn-sm btn-warning", :data => {:confirm => 'Are you sure?'}
        - if current_user.admin?(@group)
          = link_to 'delete group', group_path(@group), method: :delete, class: "btn btn-sm btn-danger", :data => {:confirm => 'Are you sure?'}
      .col-md-6
        %h2 Admins:
        =render partial: 'admin', collection: @admins
        %h3 Members:
        %ul.members
          =render partial: 'member', collection: @members

.container
  - @receipts.each_slice(3) do |receipts|
    .row
      - receipts.each do |receipt|
        .col-md-4
          = render receipt
  %hr/

.container
  .row
    .col-md-6.offset-md-3
      .post-form
        %h2.text-center Create Post
        = render 'posts/form'
        .posts
          = render partial: 'posts/post', collection: @posts