config/routes.rb
Rails.application.routes.draw do
  get 'memberships/create'
  get 'memberships/destroy'

  root to: 'pages#profile'
  get '/search', to: 'pages#search'
  get '/profile', to: 'pages#profile'

  post '/check_invitation', to: 'invitations#check_invitation'

  devise_for :users

  resources :groups do
    resources :posts, only: [:create]
    resources :receipts
  end
  resources :invitations, only: [:create, :destroy]
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :group

  has_many :contributors, dependent: :destroy
  has_many :contributing_users, through: :contributors, source: :user
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @contributors = @group.members.map {|m| [m.id, m.email]}
    @receipt = Receipt.new
    @currencies = %w[EUR USD PLN]
  end

  def create
    @group = Group.find(params[:group_id])
    @receipt = @group.receipts.build(receipt_params)
    if @receipt.save
      params[:receipt][:contributors].each do |contributor_id|
        @receipt.contributors.build(user_id: contributor_id) unless contributor_id.empty?
      end
      if @receipt.save
        redirect_to @group, notice: 'Receipt with contributors created'
      else
        redirect_to @group, notice: 'Receipt created'
      end
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @group = Group.find(params[:group_id])
    if @receipt.destroy
      redirect_to @group, notice: 'Receipt deleted'
    else
      redirect_to @group, notice: 'Could not delete the receipt'
    end
  end

  private

  def receipt_params
    params.require(:receipt).permit(:name, :currency, :amount)
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.haml
form
= simple_form_for([@group, @receipt]) do |f|
  .form-group
    = f.input :name, input_html: { class: 'form-control', placeholder: "Name" }
  .form-group
    = f.input :currency, collection: @currencies, input_html: { class: 'form-control', placeholder: "Name" }
  .form-group
    = f.input :amount, input_html: { class: 'form-control' }
  .form-group
    = f.input :contributors, as: :check_boxes, collection: @contributors, label_method: :second, value_method: :first
  .form-group
    = f.button :submit

app/views/receipts/_receipt.html.haml
.card.mb-4.box-shadow
  .card-header
    = receipt.name
  .card-body
    %p.card-text= receipt.amount
    %ul
      - receipt.contributors.each do |contributor|
        %li
          = contributor.short_email
          = contributor.debt_with_currency
    .d-flex.justify-content-between.align-items-center
      .btn-group
        = link_to "Edit", edit_group_receipt_path(id: receipt.id, group_id: @group.id), class: "button btn btn-sm btn-outline-secondary"
        = link_to "Delete", group_receipt_path(id: receipt.id, group_id: @group.id), method: :delete, class: "button btn btn-sm btn-outline-secondary"
      %small.text-muted
        = receipt.created_at

app/views/receipts/new.html.haml
new
.container
  .row
    .col-md-6.offset-md-3
      = render partial: 'form'