config/routes.rb
Rails.application.routes.draw do
  get 'memberships/create'
  get 'memberships/destroy'

  root to: 'pages#profile'
  get '/search', to: 'pages#search'
  get '/profile', to: 'pages#profile'

  post '/check_invitation', to: 'invitations#check_invitation'

  devise_for :users

  resources :groups do
    resources :posts, only: [:create]
    resources :receipts
  end
  resources :invitations, only: [:create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :read, Group do |group|
        group.member?(user)
      end
      can :manage, Group do |group|
        user.admin?(group)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  before_create :set_debt

  belongs_to :user
  belongs_to :receipt

  def set_debt
    self.debt ||= receipt.amount / receipt.contributors.size.to_f
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :invitations, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :receipts

  def member?(user)
    members.include?(user)
  end

  def has_admin?
    memberships.admin.present?
  end

  def set_admin
    memberships.first.admin!
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  validate :user_cant_be_invited_to_the_same_group_twice, :cant_invite_member_of_the_group

  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  belongs_to :group

  def user_cant_be_invited_to_the_same_group_twice
    if Invitation.where(receiver: receiver_id, group_id: group_id).exists?
      errors.add(:group_id, "cant invite same user twice")
    end
  end

  def cant_invite_member_of_the_group
    if Membership.where(user_id: receiver_id, group_id: group_id).exists?
      errors.add(:group_id, "cant invite a member")
    end
  end

end

app/models/membership.rb
class Membership < ApplicationRecord
  enum member_type: { member: 0, admin: 1 }
  validate :user_cant_join_same_group_twice, on: :create
  after_destroy :destroy_group_if_no_members

  belongs_to :user
  belongs_to :group

  def user_cant_join_same_group_twice
    if Membership.where(user_id: user_id, group_id: group_id).exists?
      errors.add(:user_id, "cant join same group twice")
    end
  end

  def destroy_group_if_no_members
    group.destroy if group.members.blank?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :user
  belongs_to :group
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :group

  has_many :contributors, dependent: :destroy
  has_many :contributing_users, through: :contributors, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :groups, through: :memberships

  has_many :sent_invitations, class_name: "Invitation", foreign_key: :sender_id
  has_many :received_invitations, class_name: "Invitation", foreign_key: :receiver_id

  has_many :posts
  has_many :contributors

  self.per_page = 10

  def self.admins(group)
    find(group.memberships.where(member_type: "admin").pluck(:user_id))
  end

  def self.filter_users(search)
    search.nil? ? all : where("email LIKE ?","%#{search}%")
  end

  def admin?(group)
    User.admins(group).include?(self)
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        @membership = current_user.memberships.build(group_id: @group.id)
        if @membership.save
          @membership.admin!
          format.html { redirect_to @group,
                        notice: 'Group created, you are now admin of this group.'}
        else
          format.html { render :new }
        end
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      redirect_to root_path
    else
    end
  end

  def show
    @group = Group.find(params[:id])
    authorize! :read, @group
    @admins = User.admins(@group)
    @members = @group.members - @admins
    @posts = @group.posts.order(created_at: :desc).decorate
    @receipts = @group.receipts.decorate
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
    @filtered_users = User.filter_users(params[:search]).paginate(:page => params[:page])
    @user_groups = current_user.groups.uniq
  end

  def profile
    @invitations = current_user.received_invitations
    @user_groups = current_user.groups.uniq
    @debts = current_user.contributors.decorate
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.group_id = params[:group_id]

    if @post.save
      respond_to do |format|
        format.html { redirect_to group_path(params[:group_id]), notice: 'post created' }
        format.js { }
      end
    else
      redirect_to group_path(params[:group_id]), notice: 'could not create post'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @contributors = @group.members.map {|m| [m.id, m.email]}
    @receipt = Receipt.new
    @currencies = %w[EUR USD PLN]
  end

  def create
    @group = Group.find(params[:group_id])
    @receipt = @group.receipts.build(receipt_params)
    if @receipt.save
      params[:receipt][:contributors].each do |contributor_id|
        @receipt.contributors.build(user_id: contributor_id) unless contributor_id.empty?
      end
      if @receipt.save
        redirect_to @group, notice: 'Receipt with contributors created'
      else
        redirect_to @group, notice: 'Receipt created'
      end
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @group = Group.find(params[:group_id])
    if @receipt.destroy
      redirect_to @group, notice: 'Receipt deleted'
    else
      redirect_to @group, notice: 'Could not delete the receipt'
    end
  end

  private

  def receipt_params
    params.require(:receipt).permit(:name, :currency, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def badge_type(group)
    current_user.admin?(group) ? badge("Admin") : badge("Member")
  end

  def badge(content)
    "<span class='badge badge-pill badge-primary'>#{content}</span>".html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-sm.bg-dark.navbar-dark
  = render 'layouts/user_links'

app/views/layouts/_user_links.html.haml
%ul.navbar-nav
  - if user_signed_in?
    - if current_user.groups.any?
      %li.nav-item= link_to 'Search', search_path, class: 'nav-link'
    %li.nav-item= link_to 'Profile', profile_path, class: 'nav-link'
    %li.nav-item= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'
  - else
    %li.nav-item= link_to 'Login', new_user_session_path, class: 'nav-link'
    %li.nav-item= link_to 'Register', new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SplitAReceipt
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = render 'shared/flash_messages' unless flash.empty?
    = yield

app/views/pages/_debt.html.haml
%li.list-group-item
  .row
    .col-md-4
      = link_to debt.receipt.group.name, group_path(debt.receipt.group)
    .col-md-4
      = debt.debt_with_currency

app/views/pages/_filtered_users.html.haml
.item-form
  = form_tag({ controller: 'invitations', action: 'create'}, method: 'post') do
    = hidden_field_tag(:sender_id, current_user.id)
    = hidden_field_tag(:receiver_id, user.id)
    .item-mail.float-left.flex-column
      = user.email
    .float-right.flex-column
      = select_tag 'group_id', options_from_collection_for_select(@user_groups, :id, :name)
      = submit_tag "invite", name: nil, id: "invite_button#{user.id}", class: 'btn btn-default btn-submit'
%br

app/views/pages/_invitation.html.haml
%li.list-group-item
  To:
  =link_to "#{invitation.group.name}", group_path(invitation.group)
  =link_to "Accept", memberships_create_path(user_id: invitation.receiver_id, group_id: invitation.group.id), class: "badge badge-pill badge-success"
  =link_to "Decline", invitation_path(invitation), method: :delete, class: "badge badge-pill badge-danger"

app/views/pages/_search_form.html.haml
= form_tag("/search", method: "get") do
  .col-md-6.offset-md-3
    %h2.text-center= label_tag(:search, "Filter users:")
    = text_field_tag(:search, nil, class: 'form-control', value: "")
    %br
    = submit_tag("Search", class: "btn btn-primary btn-lg btn-block")

app/views/pages/_user_group.html.haml
.col-md-10.offset-md-1
  %ul.list-group
    %li.list-group-item
      .row
        .col-md-8
          =link_to user_group.name, group_path(user_group)
        .col-md-2
          =badge_type(user_group)

app/views/pages/profile.html.haml
.jumbotron
  .container
    %h1.display-3= current_user.email
    =link_to 'Create a group', new_group_path, class: "btn btn-primary btn-lg mt-4"
.container
  .row
    .col-md-4
      .card
        .card-block
          %h3.card-title.text-center.my-3 Your groups:
          =render partial: "user_group", collection: @user_groups
    .col-md-4
      .card
        .card-block
          %h3.card-title.text-center.my-3 Your invitations:
          %ul.list-group
            =render partial: "invitation", collection: @invitations
    .col-md-4
      .card
        .card-block
          %h3.card-title.text-center.my-3 Your debts:
          %ul.list-group
            =render partial: "debt", collection: @debts

app/views/pages/search.html.haml
.jumbotron
  .container
    .row
      .col-md-8.offset-md-2
        =render "search_form"
.container
  .row
    .col-md-6.offset-md-3
      .digg_pagination
        =will_paginate @filtered_users
        %br
        .list-group
          =render partial: "filtered_users", collection: @filtered_users, as: :user

app/views/shared/_flash_messages.html.haml
.alert.alert-info
  - flash.each do |key, value|
    = content_tag :div, value, class: "flash #{key}"